---
- name: Setup Arch pentest workstation
  hosts: localhost
  become: true
  vars:
    user: "{{ lookup('env','SUDO_USER') | default(lookup('env','USER')) }}"
    user_home: "/home/{{ user }}"
    tools_dir: "{{ user_home }}/tools"
    wallpaper_src: "{{ playbook_dir }}/wallpaper.jpg"
    wallpaper_dst: "{{ user_home }}/Pictures/wallpaper.jpg"

  tasks:

  ###############################################################
  # INITIAL PACMAN SYNC
  ###############################################################
  - name: Update pacman cache before anything else
    ansible.builtin.pacman:
      update_cache: yes

  ###############################################################
  # ENABLE BLACKARCH REPO
  ###############################################################
  - name: Download BlackArch installer
    ansible.builtin.get_url:
      url: https://blackarch.org/strap.sh
      dest: /tmp/strap.sh
      mode: '0755'

  - name: Run BlackArch installer
    ansible.builtin.command: /tmp/strap.sh

  - name: Refresh pacman cache after enabling repo
    ansible.builtin.pacman:
      update_cache: yes

  ###############################################################
  # INSTALL YAY DEPENDENCIES
  ###############################################################
  - name: Install base-devel and git for yay build
    ansible.builtin.pacman:
      name:
        - base-devel
        - git
      state: present

  ###############################################################
  # BUILD AND INSTALL YAY
  ###############################################################
  - name: Clone yay
    become: false
    ansible.builtin.git:
      repo: https://aur.archlinux.org/yay.git
      dest: "{{ user_home }}/yay"

  - name: Build yay (as user)
    become: false
    ansible.builtin.command:
      cmd: makepkg --noconfirm -si
    args:
      chdir: "{{ user_home }}/yay"

  ###############################################################
  # MAIN PACMAN PACKAGES
  ###############################################################
  - name: Install pentest packages (pacman)
    ansible.builtin.pacman:
      name:
        - python-pip
        - python-pipx
        - go
        - wget
        - curl
        - unzip
        - gobuster
        - hashcat
        - john
        - hydra
        - sqlmap
        - impacket
        - openvpn
        - responder
        - kerbrute
        - dnsutils
        - ffuf
        - masscan
        - netcat
        - gowitness
        - evil-winrm
      state: present
      update_cache: yes

  ###############################################################
  # AUR PACKAGES
  ###############################################################
  - name: Install AUR packages with yay
    become: false
    ansible.builtin.command: >
      yay -S --noconfirm --needed
      brave-bin
      burpsuite
      slack-desktop
      extension-manager

  ###############################################################
  # CREATE TOOLS DIR
  ###############################################################
  - name: Ensure tools directory exists
    ansible.builtin.file:
      path: "{{ tools_dir }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  ###############################################################
  # GIT REPO TOOLS
  ###############################################################
  - name: Clone pentest repos
    become: false
    ansible.builtin.git:
      repo: "{{ item }}"
      dest: "{{ tools_dir }}/{{ item | basename }}"
    loop:
      - https://github.com/lefayjey/linWinPwn
      - https://github.com/garrettfoster13/sccmhunter
      - https://github.com/MWR-CyberSec/PXEThief
      - https://github.com/SpecterOps/bloodhound-cli
      - https://github.com/Lmarkussen/EvilTelnet
      - https://github.com/Lmarkussen/EvilParser
      - https://github.com/Lmarkussen/EvilFTP
      - https://github.com/Lmarkussen/Bruteforce_wordlist_nor
      - https://github.com/OleFredrik1/remoteKrbRelayx

  ###############################################################
  # FONTS & WALLPAPER
  ###############################################################
  - name: Create pictures directory
    ansible.builtin.file:
      path: "{{ user_home }}/Pictures"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy wallpaper from repo
    ansible.builtin.copy:
      src: "{{ wallpaper_src }}"
      dest: "{{ wallpaper_dst }}"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Install Hack Nerd Font zip
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip
      dest: /usr/share/fonts
      remote_src: yes

  - name: Update font cache
    ansible.builtin.command: fc-cache -f -v

  ###############################################################
  # GNOME EXTENSIONS + THEME
  ###############################################################
  - name: Install GNOME extension manager (yay)
    become: false
    ansible.builtin.command: yay -S --noconfirm extension-manager

  - name: Download Dracula theme
    ansible.builtin.git:
      repo: https://github.com/dracula/gtk.git
      dest: "{{ user_home }}/.themes/Dracula"
    become: false

  - name: Set GTK theme
    become: false
    ansible.builtin.command:
      cmd: gsettings set org.gnome.desktop.interface gtk-theme 'Dracula'

  ###############################################################
  # FISH SHELL CONFIG
  ###############################################################
  - name: Install fish shell
    ansible.builtin.pacman:
      name: fish
      state: present

  - name: Change shell to fish for user
    ansible.builtin.user:
      name: "{{ user }}"
      shell: /usr/bin/fish

