---
- name: Setup Arch pentest workstation
  hosts: localhost
  become: true
  vars:
    user: "{{ ansible_env.SUDO_USER }}"
    user_home: "/home/{{ ansible_env.SUDO_USER }}"
    wallpaper_src: "{{ playbook_dir }}/wallpaper.jpg"
    wallpaper_dest: "{{ user_home }}/Pictures/wallpaper.jpg"

  tasks:
  ###############################################################
  # BLACKARCH REPO
  ###############################################################
  - name: Download BlackArch strap script
    ansible.builtin.get_url:
      url: https://blackarch.org/strap.sh
      dest: /tmp/strap.sh
      mode: '0755'

  - name: Install BlackArch repository
    command: bash /tmp/strap.sh

  ###############################################################
  # BASE SYSTEM PACKAGES
  ###############################################################
  - name: Install base system reqs (pacman)
    ansible.builtin.pacman:
      update_cache: true
      name:
        - base-devel
        - go
        - wget
        - curl
        - unzip
        - git
        - reflector

  ###############################################################
  # SETUP YAY
  ###############################################################
  - name: Clone yay
    become_user: "{{ user }}"
    ansible.builtin.git:
      repo: "https://aur.archlinux.org/yay.git"
      dest: "{{ user_home }}/yay"
      update: yes

  - name: Build yay (no install here)
    become_user: "{{ user }}"
    command: makepkg --noconfirm -s
    args:
      chdir: "{{ user_home }}/yay"

  - name: Install yay package (as root)
    command: pacman -U --noconfirm yay-*.pkg.tar.*
    args:
      chdir: "{{ user_home }}/yay"

  ###############################################################
  # PENTEST PACKAGES (pacman)
  ###############################################################
  - name: Install pentest packages (pacman)
    ansible.builtin.pacman:
      name:
        - gobuster
        - hashcat
        - john
        - hydra
        - sqlmap
        - impacket
        - openvpn
        - responder
        - kerbrute
        - dnsutils
        - ffuf
        - masscan
        - netcat
        - gowitness
        - evil-winrm
        - tmux
        - fish
      state: present
      update_cache: true

  - name: Set fish as default shell
    command: chsh -s /usr/bin/fish "{{ user }}"

  ###############################################################
  # AUR PACKAGES VIA YAY
  ###############################################################
  - name: Install AUR packages with yay
    become_user: "{{ user }}"
    command: yay -S --noconfirm --needed brave-bin burpsuite slack-desktop extension-manager flatpak

  ###############################################################
  # FLATPAKS
  ###############################################################
  - name: Install obfuscate (flatpak)
    become_user: "{{ user }}"
    command: flatpak install -y app.drey.Obfuscate

  ###############################################################
  # GNOME EXTENSIONS
  ###############################################################
  - name: Enable user-theme extension
    become_user: "{{ user }}"
    command: gsettings set org.gnome.shell.extensions.user-theme name Dracula

  ###############################################################
  # WALLPAPER & FONT
  ###############################################################
  - name: Create Pictures folder
    file:
      path: "{{ user_home }}/Pictures"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy wallpaper
    copy:
      src: "{{ wallpaper_src }}"
      dest: "{{ wallpaper_dest }}"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Set wallpaper
    become_user: "{{ user }}"
    command: gsettings set org.gnome.desktop.background picture-uri "file://{{ wallpaper_dest }}"

  - name: Download Nerd Font
    become_user: "{{ user }}"
    ansible.builtin.get_url:
      url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip"
      dest: "{{ user_home }}/Hack.zip"

  - name: Extract Nerd Font
    become_user: "{{ user }}"
    ansible.builtin.unarchive:
      src: "{{ user_home }}/Hack.zip"
      dest: "{{ user_home }}/.local/share/fonts"
      remote_src: true

  ###############################################################
  # GIT TOOL REPOS
  ###############################################################
  - name: Create tools directory
    file:
      path: "{{ user_home }}/tools"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Clone pentest repos
    become_user: "{{ user }}"
    ansible.builtin.git:
      repo: "{{ item }}"
      dest: "{{ user_home }}/tools/{{ item | basename }}"
      update: yes
    loop:
      - https://github.com/lefayjey/linWinPwn
      - https://github.com/garrettfoster13/sccmhunter
      - https://github.com/MWR-CyberSec/PXEThief
      - https://github.com/SpecterOps/bloodhound-cli
      - https://github.com/Lmarkussen/EvilTelnet
      - https://github.com/Lmarkussen/EvilParser
      - https://github.com/Lmarkussen/EvilFTP
      - https://github.com/Lmarkussen/Bruteforce_wordlist_nor
      - https://github.com/OleFredrik1/remoteKrbRelayx

  ###############################################################
  # FINAL MESSAGE
  ###############################################################
  - name: Final message
    ansible.builtin.debug:
      msg: |
        ✔ Setup Complete!
        🔒 Logout/Login required for fish shell + docker group
        🎯 You are now running a fully weaponized pentest workstation.

