---
- name: BlackArch + Pentest Desktop Setup
  hosts: localhost
  become: true
  vars:
    user: lars
    user_home: "/home/{{ user }}"

  tasks:

#################################################################
# BLACKARCH REPO
#################################################################
    - name: Install BlackArch repository
      ansible.builtin.shell: |
        curl -fsSL https://blackarch.org/strap.sh | bash
      args:
        creates: /etc/pacman.d/blackarch-mirrorlist

    - name: Update package databases
      ansible.builtin.pacman:
        update_cache: true

#################################################################
# PACMAN PACKAGES
#################################################################
    - name: Install pentest packages (pacman)
      ansible.builtin.pacman:
        name:
          - base-devel
          - go
          - docker
          - docker-compose
          - grc
          - wget
          - curl
          - unzip
          - python-pip
          - python-pipx
          - gobuster
          - hashcat
          - john
          - hydra
          - sqlmap
          - impacket
          - openvpn
          - responder
          - kerbrute
          - dnsutils
          - ffuf
          - ghostty
          - netexec
          - nmap
          - masscan
          - netcat
          - gowitness
          - evil-winrm
          - tmux
          - fish
        state: present

#################################################################
# CREATE TOOLS DIRECTORY
#################################################################
    - name: Create Tools directory
      ansible.builtin.file:
        path: "{{ user_home }}/Tools"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

#################################################################
# CLONE REPOS
#################################################################
    - name: Clone pentest repos
      ansible.builtin.git:
        repo: "{{ item }}"
        dest: "{{ user_home }}/Tools/{{ item.split('/')[-1] }}"
      loop:
        - https://github.com/lefayjey/linWinPwn
        - https://github.com/garrettfoster13/sccmhunter
        - https://github.com/MWR-CyberSec/PXEThief
        - https://github.com/SpecterOps/bloodhound-cli
        - https://github.com/Lmarkussen/EvilTelnet
        - https://github.com/Lmarkussen/EvilParser
        - https://github.com/Lmarkussen/EvilFTP
        - https://github.com/Lmarkussen/Bruteforce_wordlist_nor
        - https://github.com/OleFredrik1/remoteKrbRelayx
        - https://github.com/login-securite/DonPAPI
      become_user: "{{ user }}"

#################################################################
# INSTALL HACK NERD FONT
#################################################################
    - name: Download Hack Nerd Font
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip
        dest: "{{ user_home }}/Hack.zip"

    - name: Create local fonts directory
      ansible.builtin.file:
        path: "{{ user_home }}/.local/share/fonts"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Extract Hack font
      ansible.builtin.unarchive:
        src: "{{ user_home }}/Hack.zip"
        dest: "{{ user_home }}/.local/share/fonts"
        remote_src: yes
      become_user: "{{ user }}"

    - name: Update font cache
      ansible.builtin.shell: fc-cache -f

#################################################################
# SET HACK FONT AS DEFAULT
#################################################################
    - name: Set GNOME monospace font to Hack Nerd Font
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        gsettings set org.gnome.desktop.interface monospace-font-name 'Hack Nerd Font Mono 11'

    - name: Set GNOME interface font to Hack Nerd Font
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        gsettings set org.gnome.desktop.interface font-name 'Hack Nerd Font Regular 11'

#################################################################
# WALLPAPER
#################################################################
    - name: Copy bundled wallpaper
      ansible.builtin.copy:
        src: wallpaper.jpg
        dest: "{{ user_home }}/Pictures/wallpaper.jpg"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Set wallpaper
      ansible.builtin.shell: |
        gsettings set org.gnome.desktop.background picture-uri "file://{{ user_home }}/Pictures/wallpaper.jpg"
        gsettings set org.gnome.desktop.background picture-uri-dark "file://{{ user_home }}/Pictures/wallpaper.jpg"
      become_user: "{{ user }}"

#################################################################
# TMUX CONFIG
#################################################################
    - name: Create tmux config directory
      ansible.builtin.file:
        path: "{{ user_home }}/.config/tmux"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Copy tmux.conf
      ansible.builtin.copy:
        src: tmux.conf
        dest: "{{ user_home }}/.config/tmux/tmux.conf"
        owner: "{{ user }}"
        group: "{{ user }}"

#################################################################
# FISH CONFIG
#################################################################
    - name: Create fish config directory
      ansible.builtin.file:
        path: "{{ user_home }}/.config/fish"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Copy fish config
      ansible.builtin.copy:
        src: config.fish
        dest: "{{ user_home }}/.config/fish/config.fish"
        owner: "{{ user }}"
        group: "{{ user }}"

#################################################################
# SET DEFAULT SHELL TO FISH
#################################################################
    - name: Set fish default shell
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /usr/bin/fish


#################################################################
# GNOME EXTENSIONS (better visibility)
#################################################################

    - name: Install caffeine extension
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        extension-manager install caffeine@patapon.info

    - name: Install dash-to-dock extension
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        extension-manager install dash-to-dock@micxgx.gmail.com

    - name: Install user-theme extension
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        extension-manager install user-theme@gnome-shell-extensions.gcampax.github.com

    - name: Install tray icons reloaded extension
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        extension-manager install trayIconsReloaded@selfmade.pl

    - name: Install blur my shell extension
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        extension-manager install blur-my-shell@aunetx

#################################################################
# DRACULA GTK THEME
#################################################################
    - name: Clone Dracula GTK Theme
      become_user: "{{ user }}"
      ansible.builtin.git:
        repo: "https://github.com/dracula/gtk"
        dest: "{{ user_home }}/.themes/Dracula"

    - name: Apply Dracula GTK theme
      become_user: "{{ user }}"
      ansible.builtin.shell: |
        gsettings set org.gnome.desktop.interface gtk-theme 'Dracula'


#################################################################
# DONE
#################################################################
    - name: Finished
      ansible.builtin.debug:
        msg: "Setup completed. Reboot is recommended"

