---
- name: Setup Arch pentest workstation
  hosts: localhost
  become: true

  vars:
    user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    user_home: "/home/{{ user }}"
    tools_dir: "{{ user_home }}/tools"

  tasks:

    ############################################################
    # BASE & MIRRORS
    ############################################################

    - name: Install base prerequisites
      ansible.builtin.pacman:
        name:
          - git
          - base-devel
          - reflector
          - curl
          - wget
        state: present
        update_cache: yes

    - name: Optimize pacman mirrors
      ansible.builtin.command:
        cmd: reflector --latest 20 --sort rate --save /etc/pacman.d/mirrorlist

    - name: Update pacman database and system
      ansible.builtin.pacman:
        update_cache: yes
        upgrade: yes

    ############################################################
    # BLACKARCH REPO
    ############################################################

    - name: Download BlackArch strap.sh
      ansible.builtin.get_url:
        url: https://blackarch.org/strap.sh
        dest: /tmp/strap.sh
        mode: '0755'

    - name: Run BlackArch strap.sh
      ansible.builtin.command:
        cmd: /tmp/strap.sh

    - name: Refresh pacman after adding BlackArch
      ansible.builtin.pacman:
        update_cache: yes

    ############################################################
    # CORE PACKAGES VIA PACMAN (INCLUDING yay)
    ############################################################

    - name: Install core tools from pacman
      ansible.builtin.pacman:
        name:
          - yay
          - docker
          - docker-compose
          - tmux
          - fish
          - grc
          - fzf
          - seclists
          - python
          - python-pip
          - python-pipx
        state: present

    ############################################################
    # PENTEST PACKAGES (PACMAN)
    ############################################################

    - name: Install pentest packages from pacman
      ansible.builtin.pacman:
        name:
          - hashcat
          - netexec
          - john
          - hydra
          - sqlmap
          - impacket
          - openvpn
          - responder
          - kerbrute
          - gobuster
          - evil-winrm
          - gowitness
          - masscan
          - netcat
          - certipy
          - dnsutils
          - ffuf
        state: present

    ############################################################
    # DOCKER SETUP
    ############################################################

    - name: Enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: true

    - name: Notify user about docker group
      ansible.builtin.debug:
        msg: "You must log out and back in for docker group permissions to apply."

    ############################################################
    # SUDOERS FIX FOR yay (NO PASSWORD FOR PACMAN)
    ############################################################

    - name: Allow user to run pacman without password for yay
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/99-{{ user }}-pacman"
        content: "{{ user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman\n"
        mode: '0440'

    ############################################################
    # AUR PACKAGES VIA yay
    ############################################################

    - name: Install AUR packages with yay
      become: false
      ansible.builtin.command:
        cmd: yay -S --noconfirm --needed brave-bin burpsuite slack-desktop extension-manager
      args:
        chdir: "{{ user_home }}"

    ############################################################
    # CREATE tools DIR
    ############################################################

    - name: Create tools directory
      ansible.builtin.file:
        path: "{{ tools_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    ############################################################
    # CLONE ALL OFFENSIVE REPOS
    ############################################################

    - name: Clone offensive tools into ~/tools
      become: false
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ tools_dir }}/{{ item.name }}"
      loop:
        - { name: "linWinPwn", repo: "https://github.com/lefayjey/linWinPwn" }
        - { name: "sccmhunter", repo: "https://github.com/garrettfoster13/sccmhunter" }
        - { name: "PXEThief", repo: "https://github.com/MWR-CyberSec/PXEThief" }
        - { name: "bloodhound-cli", repo: "https://github.com/SpecterOps/bloodhound-cli" }
        - { name: "EvilTelnet", repo: "https://github.com/Lmarkussen/EvilTelnet" }
        - { name: "EvilParser", repo: "https://github.com/Lmarkussen/EvilParser" }
        - { name: "EvilFTP", repo: "https://github.com/Lmarkussen/EvilFTP" }
        - { name: "Bruteforce_wordlist_nor", repo: "https://github.com/Lmarkussen/Bruteforce_wordlist_nor" }
        - { name: "remoteKrbRelayx", repo: "https://github.com/OleFredrik1/remoteKrbRelayx" }

    ############################################################
    # SHELL CONFIG
    ############################################################

    - name: Ensure config directories exist
      ansible.builtin.file:
        path: "{{ user_home }}/.config/{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'
      loop:
        - fish
        - tmux

    - name: Copy fish config
      ansible.builtin.copy:
        src: config.fish
        dest: "{{ user_home }}/.config/fish/config.fish"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Copy tmux config
      ansible.builtin.copy:
        src: tmux.conf
        dest: "{{ user_home }}/.config/tmux/tmux.conf"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Set fish as default shell
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /usr/bin/fish

    ############################################################
    # FINAL SUMMARY
    ############################################################

    - name: Final summary
      ansible.builtin.debug:
        msg: |
          ✅ Arch BlackArch pentest workstation ready.
          🧰 Tools dir: {{ tools_dir }}
          🐚 Shell: fish (log out / log in to use)
          🐳 Docker: enabled (log out / log in for group)
          📦 AUR apps installed via yay without prompts.

