---
- hosts: localhost
  gather_facts: true
  vars:
    user: "{{ lookup('env','USER') }}"
    user_home: "/home/{{ lookup('env','USER') }}"

  tasks:
  ###############################################################
  # BLACKARCH REPO
  ###############################################################
  - name: Install BlackArch repository
    command: sh -c "$(curl -fsSL https://blackarch.org/strap.sh)"
    args:
      creates: /etc/pacman.d/blackarch-mirrorlist

  - name: Update package databases
    ansible.builtin.pacman:
      update_cache: true

  ###############################################################
  # CLEAN YAY IF EXISTS
  ###############################################################
  - name: Remove old yay directory
    file:
      path: "{{ user_home }}/yay"
      state: absent

  ###############################################################
  # CLONE YAY
  ###############################################################
  - name: Clone yay
    ansible.builtin.git:
      repo: https://aur.archlinux.org/yay.git
      dest: "{{ user_home }}/yay"

  - name: Fix permissions on yay folder
    file:
      path: "{{ user_home }}/yay"
      owner: "{{ user }}"
      group: "{{ user }}"
      recurse: yes

  ###############################################################
  # BUILD YAY AS USER
  ###############################################################
  - name: Build yay (as user)
    become_user: "{{ user }}"
    command: makepkg --noconfirm -si --needed
    args:
      chdir: "{{ user_home }}/yay"

  ###############################################################
  # PACMAN PACKAGES
  ###############################################################
  - name: Install base packages (pacman)
    ansible.builtin.pacman:
      name:
        - base-devel
        - go
        - wget
        - curl
        - unzip
        - python-pip
        - python-pipx
        - tmux
        - fish
        - netexec
      state: present

  ###############################################################
  # SET FISH DEFAULT SHELL
  ###############################################################
  - name: Set fish as default shell
    command: chsh -s /usr/bin/fish {{ user }}

  ###############################################################
  # AUR PACKAGES (YAY)
  ###############################################################
  - name: Install AUR packages with yay
    become_user: "{{ user }}"
    command: yay -S --noconfirm --needed brave-bin burpsuite extension-manager flatpak

  ###############################################################
  # FLATPAK
  ###############################################################
  - name: Install Obfuscate (flatpak)
    become_user: "{{ user }}"
    command: flatpak install -y com.github.hluk.copyq

  ###############################################################
  # CLONE GITHUB REPOS
  ###############################################################
  - name: Clone pentest repos
    ansible.builtin.git:
      repo: "{{ item }}"
      dest: "{{ user_home }}/tools/{{ item | basename }}"
    loop:
      - https://github.com/lefayjey/linWinPwn
      - https://github.com/garrettfoster13/sccmhunter
      - https://github.com/MWR-CyberSec/PXEThief
      - https://github.com/SpecterOps/bloodhound-cli
      - https://github.com/Lmarkussen/EvilTelnet
      - https://github.com/Lmarkussen/EvilParser
      - https://github.com/Lmarkussen/EvilFTP
      - https://github.com/Lmarkussen/Bruteforce_wordlist_nor
      - https://github.com/OleFredrik1/remoteKrbRelayx

  ###############################################################
  # THEMING
  ###############################################################
  - name: Create theme dir
    file:
      path: "{{ user_home }}/.themes"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy wallpaper
    ansible.builtin.copy:
      src: wallpaper.jpg
      dest: "{{ user_home }}/Pictures/wallpaper.jpg"
      owner: "{{ user }}"
      group: "{{ user }}"


