---
- hosts: localhost
  become: yes
  vars:
    user: "{{ lookup('env','USER') }}"
    user_home: "/home/{{ user }}"
    timestamp: "{{ lookup('pipe','date +%Y%m%d-%H%M') }}"
    wallpaper_src: "{{ playbook_dir }}/wallpaper.jpg"
    wallpaper_dest: "{{ user_home }}/Pictures/wallpaper.jpg"

  tasks:
  ###############################################################
  # BLACKARCH REPO
  ###############################################################
  - name: Install BlackArch repository
    shell: "curl -s https://blackarch.org/strap.sh | bash"

  ###############################################################
  # PACMAN PENTEST PACKAGES
  ###############################################################
  - name: Install pentest packages (pacman)
    ansible.builtin.pacman:
      name:
        - gobuster
        - hashcat
        - john
        - hydra
        - sqlmap
        - impacket
        - openvpn
        - responder
        - kerbrute
        - dnsutils
        - ffuf
        - masscan
        - netcat
        - gowitness
        - evil-winrm
      state: present
      update_cache: true

  ###############################################################
  # BUILD AND INSTALL YAY
  ###############################################################
  - name: Remove existing yay build
    file:
      path: "{{ user_home }}/yay"
      state: absent

  - name: Clone yay
    ansible.builtin.git:
      repo: https://aur.archlinux.org/yay.git
      dest: "{{ user_home }}/yay"

  - name: Build yay (as user)
    command: makepkg --noconfirm -si --needed
    become_user: "{{ user }}"
    args:
      chdir: "{{ user_home }}/yay"

  ###############################################################
  # AUR PACKAGES USING YAY (ROOT INSTALL)
  ###############################################################
  - name: Install AUR packages with yay (as root)
    become: true
    command: yay -S --noconfirm --needed --answerclean All brave-bin burpsuite slack-desktop extension-manager flatpak

  ###############################################################
  # FLATPAK INSTALLS
  ###############################################################
  - name: Install Obfuscate (flatpak)
    become_user: "{{ user }}"
    command: flatpak install -y com.obfuscate.Obfuscate

  ###############################################################
  # CLONE GITHUB REPOSITORIES
  ###############################################################
  - name: Clone pentest repos
    ansible.builtin.git:
      repo: "{{ item }}"
      dest: "{{ user_home }}/Tools/{{ item.split('/')[-1] }}"
    with_items:
      - https://github.com/lefayjey/linWinPwn
      - https://github.com/garrettfoster13/sccmhunter
      - https://github.com/MWR-CyberSec/PXEThief
      - https://github.com/SpecterOps/bloodhound-cli
      - https://github.com/Lmarkussen/EvilTelnet
      - https://github.com/Lmarkussen/EvilParser
      - https://github.com/Lmarkussen/EvilFTP
      - https://github.com/Lmarkussen/Bruteforce_wordlist_nor
      - https://github.com/OleFredrik1/remoteKrbRelayx

  ###############################################################
  # WALLPAPER
  ###############################################################
  - name: Ensure Pictures directory exists
    file:
      path: "{{ user_home }}/Pictures"
      state: directory
      mode: '0755'
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy wallpaper from local repo
    copy:
      src: "{{ wallpaper_src }}"
      dest: "{{ wallpaper_dest }}"
      owner: "{{ user }}"
      group: "{{ user }}"

  ###############################################################
  # GNOME EXTENSION MANAGER
  ###############################################################
  - name: Install extension manager
    become: true
    command: yay -S --noconfirm extension-manager

  ###############################################################
  # DRACULA THEME
  ###############################################################
  - name: Create local theme folder
    file:
      path: "{{ user_home }}/.themes"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: Download Dracula GTK
    become_user: "{{ user }}"
    git:
      re

