---
- name: Setup Arch pentest workstation
  hosts: localhost
  become: true
  become_method: sudo

  vars:
    user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    user_home: "/home/{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    tools_dir: "{{ user_home }}/tools"

    pacman_packages:
      - base-devel
      - git
      - curl
      - wget
      - reflector
      - nmap
      - gobuster
      - wireshark-cli
      - jq
      - metasploit
      - bloodhound
      - virtualbox
      - signal-desktop
      - qbittorrent
      - dbeaver
      - thunar
      - thunar-archive-plugin
      - go
      - rust
      - docker
      - docker-compose
      - fish
      - tmux
      - grc
      - fzf
      - seclists

    aur_packages:
      - brave-bin
      - burpsuite
      - slack-desktop
      - extension-manager

    github_tools:
      - { repo: "https://github.com/lefayjey/linWinPwn.git",           name: "linWinPwn" }
      - { repo: "https://github.com/garrettfoster13/sccmhunter.git",   name: "sccmhunter" }
      - { repo: "https://github.com/MWR-CyberSec/PXEThief.git",        name: "PXEThief" }
      - { repo: "https://github.com/SpecterOps/bloodhound-cli.git",    name: "bloodhound-cli" }
      - { repo: "https://github.com/Lmarkussen/EvilTelnet.git",        name: "EvilTelnet" }
      - { repo: "https://github.com/Lmarkussen/EvilParser.git",        name: "EvilParser" }
      - { repo: "https://github.com/Lmarkussen/EvilFTP.git",           name: "EvilFTP" }
      - { repo: "https://github.com/Lmarkussen/Bruteforce_wordlist_nor.git", name: "Bruteforce_wordlist_nor" }

  tasks:
    #################################################################
    # PACMAN BASE
    #################################################################
    - name: Ensure archlinux-keyring is installed and cache updated
      ansible.builtin.pacman:
        name: archlinux-keyring
        state: present
        update_cache: yes

    - name: Install base packages
      ansible.builtin.pacman:
        name: "{{ pacman_packages }}"
        state: present
        update_cache: yes

    #################################################################
    # DOCKER
    #################################################################
    - name: Enable and start Docker
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: yes

    #################################################################
    # YAY INSTALL (BUILD ONLY, THEN INSTALL)
    #################################################################
    - name: Clone yay AUR helper
      become: false
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ user_home }}/yay"

    - name: Clean previous yay build artifacts
      become: false
      ansible.builtin.shell: |
        rm -rf "{{ user_home }}/yay/pkg" "{{ user_home }}/yay/src" "{{ user_home }}/yay"/*.pkg.tar.zst
      args:
        executable: /bin/bash

    - name: Build yay package (no install)
      become: false
      ansible.builtin.shell: |
        cd "{{ user_home }}/yay"
        makepkg --noconfirm -f -s
      args:
        executable: /bin/bash

    - name: Install yay package as root
      ansible.builtin.shell: |
        pacman -U --noconfirm "{{ user_home }}"/yay/*.pkg.tar.zst
      args:
        executable: /bin/bash

    #################################################################
    # SUDOERS FOR YAY/PACMAN (FOR AUR INSTALLS)
    #################################################################
    - name: Allow yay to use sudo without password
      ansible.builtin.copy:
        dest: /etc/sudoers.d/10-yay
        content: |
          Cmnd_Alias YAY_CMDS = /usr/bin/pacman, /usr/bin/yay
          {{ user }} ALL=(ALL) NOPASSWD: YAY_CMDS
        mode: '0440'

    #################################################################
    # AUR PACKAGES
    #################################################################
    - name: Install AUR packages with yay
      become: false
      ansible.builtin.shell: |
        yay -S --needed --noconfirm --noprogressbar {{ item }}
      loop: "{{ aur_packages }}"
      args:
        executable: /bin/bash

    #################################################################
    # GITHUB TOOLS
    #################################################################
    - name: Create tools directory
      ansible.builtin.file:
        path: "{{ tools_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Clone pentest tools
      become: false
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ tools_dir }}/{{ item.name }}"
      loop: "{{ github_tools }}"

    #################################################################
    # CONFIGS
    #################################################################
    - name: Ensure fish config directory exists
      become: false
      ansible.builtin.file:
        path: "{{ user_home }}/.config/fish"
        state: directory

    - name: Copy fish config
      ansible.builtin.copy:
        src: config.fish
        dest: "{{ user_home }}/.config/fish/config.fish"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Ensure tmux config directory exists
      ansible.builtin.file:
        path: "{{ user_home }}/.config/tmux"
        state: directory

    - name: Copy tmux config
      ansible.builtin.copy:
        src: tmux.conf
        dest: "{{ user_home }}/.config/tmux/tmux.conf"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    #################################################################
    # SHELL
    #################################################################
    - name: Set fish as default shell safely
      ansible.builtin.shell: |
        if command -v fish >/dev/null 2>&1; then
          chsh -s /usr/bin/fish "{{ user }}"
        fi
      args:
        executable: /bin/bash

