---
- name: Setup Arch with BlackArch, packages, and tool repos
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root

  vars:

    pacman_packages:
      - nmap
      - gobuster
      - wireshark-cli
      - jq
      - metasploit
      - bloodhound
      - neo4j
      - ghostty
      - brave-bin
      - burpsuite
      - slack-desktop
      - virtualbox
      - signal-desktop
      - qbittorrent
      - wps-office
      - dbeaver
      - thunar
      - thunar-archive-plugin

    flatpak_packages:
      - md.obsidian.Obsidian
      - com.brave.Browser
      - com.proton.pass
      - org.signal.Signal
      - com.github.zocker_160.Obfuscate   # obfuscation tool

    github_tools:
      - repo: https://github.com/ropnop/kerbrute.git
        dest: /opt/kerbrute
      - repo: https://github.com/carlospolop/PEASS-ng.git
        dest: /opt/peass
      - repo: https://github.com/samratashok/nishang.git
        dest: /opt/nishang
      - repo: https://github.com/lefayjey/linWinPwn.git
        dest: /opt/linWinPwn
      - repo: https://github.com/garrettfoster13/sccmhunter.git
        dest: /opt/sccmhunter
      - repo: https://github.com/MWR-CyberSec/PXEThief.git
        dest: /opt/PXEThief
      - repo: https://github.com/SpecterOps/bloodhound-cli.git
        dest: /opt/bloodhound-cli
      - repo: https://github.com/Lmarkussen/EvilTelnet.git
        dest: /opt/EvilTelnet
      - repo: https://github.com/Lmarkussen/EvilParser.git
        dest: /opt/EvilParser
      - repo: https://github.com/Lmarkussen/EvilFTP.git
        dest: /opt/EvilFTP
      - repo: https://github.com/Lmarkussen/Bruteforce_wordlist_nor.git
        dest: /opt/Bruteforce_wordlist_nor

  tasks:

    #####################################################################
    #   BLACKARCH REPOSITORY
    #####################################################################
    - name: Install prerequisites
      community.general.pacman:
        name:
          - curl
          - wget
        state: present
        update_cache: yes

    - name: Download BlackArch bootstrap script
      ansible.builtin.get_url:
        url: https://blackarch.org/strap.sh
        dest: /root/strap.sh
        mode: '0700'

    - name: Install BlackArch repo
      ansible.builtin.shell: /root/strap.sh
      args:
        creates: /etc/pacman.d/blackarch-mirrorlist


    #####################################################################
    #   PACMAN PACKAGES
    #####################################################################
    - name: Update pacman cache
      community.general.pacman:
        update_cache: yes

    - name: Install pacman packages
      community.general.pacman:
        name: "{{ pacman_packages }}"
        state: present


    #####################################################################
    #   FLATPAK PACKAGES
    #####################################################################
    - name: Install flatpak
      community.general.pacman:
        name: flatpak
        state: present

    - name: Add flathub repo
      ansible.builtin.shell: |
        flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpak packages
      ansible.builtin.shell: "flatpak install -y flathub {{ item }}"
      loop: "{{ flatpak_packages }}"


    #####################################################################
    #   GITHUB REPOS
    #####################################################################
    - name: Install git
      community.general.pacman:
        name: git
        state: present

    - name: Clone GitHub tools
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: master
      loop: "{{ github_tools }}"

    - name: Set perm 755 recursively on /opt tools
      ansible.builtin.file:
        path: "{{ item.dest }}"
        recurse: yes
        mode: "0755"
      loop: "{{ github_tools }}"
