---
- name: Setup Arch pentest workstation
  hosts: localhost
  become: true
  vars:
    user: lars
    user_home: "/home/lars"

  tasks:

  ###############################################################
  # PACMAN PACKAGES
  ###############################################################
  - name: Install pentest packages (pacman)
    ansible.builtin.pacman:
      name:
        - base-devel
        - go
        - wget
        - curl
        - unzip
        - python-pip
        - python-pipx
        - gobuster
        - hashcat
        - john
        - hydra
        - sqlmap
        - impacket
        - openvpn
        - responder
        - kerbrute
        - dnsutils
        - ffuf
        - masscan
        - netcat
        - gowitness
        - evil-winrm
      state: present
      update_cache: true

  ###############################################################
  # YAY BUILD & INSTALL
  ###############################################################
  - name: Clone yay
    ansible.builtin.git:
      repo: "https://aur.archlinux.org/yay.git"
      dest: "{{ user_home }}/yay"
      clone: yes
    become_user: "{{ user }}"

  - name: Build yay
    ansible.builtin.command:
      cmd: "makepkg --noconfirm -si"
      chdir: "{{ user_home }}/yay"
    become_user: "{{ user }}"
    environment:
      PKGDEST: "{{ user_home }}/yay"

  ###############################################################
  # AUR via yay (BRAVE)
  ###############################################################
  - name: Install brave-bin (yay)
    ansible.builtin.command:
      cmd: "yay -S --noconfirm --needed brave-bin"
    become_user: "{{ user }}"

  ###############################################################
  # AUR via yay (BURP)
  ###############################################################
  - name: Install burpsuite (yay)
    ansible.builtin.command:
      cmd: "yay -S --noconfirm --needed burpsuite"
    become_user: "{{ user }}"

  ###############################################################
  # AUR via yay (SLACK)
  ###############################################################
  - name: Install slack-desktop (yay)
    ansible.builtin.command:
      cmd: "yay -S --noconfirm --needed slack-desktop"
    become_user: "{{ user }}"

  ###############################################################
  # AUR via yay (Extension Manager)
  ###############################################################
  - name: Install extension-manager (yay)
    ansible.builtin.command:
      cmd: "yay -S --noconfirm --needed extension-manager"
    become_user: "{{ user }}"

  ###############################################################
  # CLONE GITHUB TOOLS
  ###############################################################
  - name: Clone pentest repos
    ansible.builtin.git:
      repo: "{{ item }}"
      dest: "{{ user_home }}/tools/{{ item.split('/')[-1] }}"
    with_items:
      - https://github.com/lefayjey/linWinPwn
      - https://github.com/garrettfoster13/sccmhunter
      - https://github.com/MWR-CyberSec/PXEThief
      - https://github.com/SpecterOps/bloodhound-cli
      - https://github.com/Lmarkussen/EvilTelnet
      - https://github.com/Lmarkussen/EvilParser
      - https://github.com/Lmarkussen/EvilFTP
      - https://github.com/Lmarkussen/Bruteforce_wordlist_nor
      - https://github.com/OleFredrik1/remoteKrbRelayx
    become_user: "{{ user }}"

  ###############################################################
  # WALLPAPER
  ###############################################################
  - name: Ensure Pictures directory exists
    ansible.builtin.file:
      path: "{{ user_home }}/Pictures"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy wallpaper locally
    ansible.builtin.copy:
      src: "wallpaper.jpg"
      dest: "{{ user_home }}/Pictures/wallpaper.jpg"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: "0644"

  ###############################################################
  # GNOME EXTENSIONS
  ###############################################################
  - name: Install gnome extensions (meta)
    ansible.builtin.pacman:
      name: gnome-shell-extensions
      state: present

  ###############################################################
  # FONTS
  ###############################################################
  - name: Ensure fonts dir exists
    ansible.builtin.file:
      path: "/usr/share/fonts/Hack"
      state: directory

  - name: Install Hack Nerd Font
    ansible.builtin.unarchive:
      src: "Hack.zip"
      dest: "/usr/share/fonts/Hack"
      remote_src: false

  - name: Rebuild font cache
    ansible.builtin.command: fc-cache -fv

  ###############################################################
  # GNOME THEMES AND SETTINGS
  ###############################################################
  - name: Set wallpaper
    become_user: "{{ user }}"
    ansible.builtin.command:
      cmd: "gsettings set org.gnome.desktop.background picture-uri 'file://{{ user_home }}/Pictures/wallpaper.jpg'"

  - name: Monospace font setting
    become_user: "{{ user }}"
    ansible.builtin.command:
      cmd: "gsettings set org.gnome.desktop.interface monospace-font-name 'Hack Nerd Font 11'"

  - name: UI font setting
    become_user: "{{ user }}"
    ansible.builtin.command:
      cmd: "gsettings set org.gnome.desktop.interface font-name 'Hack Nerd Font 11'"

  ###############################################################
  # DONE
  ###############################################################
  - name: Script finished!
    ansible.builtin.debug:
      msg: "Arch pentest setup finished successfully 🚀"

