---
- name: Setup Arch with BlackArch and pentest tooling
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root

  vars:
    user: "{{ ansible_env.SUDO_USER }}"
    user_home: "/home/{{ ansible_env.SUDO_USER }}"
    tools_dir: "/home/{{ ansible_env.SUDO_USER }}/tools"

    pacman_packages:
      - nmap
      - gobuster
      - wireshark-cli
      - jq
      - metasploit
      - bloodhound
      - virtualbox
      - signal-desktop
      - qbittorrent
      - dbeaver
      - thunar
      - thunar-archive-plugin
      - go
      - rust
      - base-devel
      - fish
      - tmux
      - grc
      - docker
      - docker-compose
      - fzf

    aur_packages:
      - brave-bin
      - burpsuite
      - slack-desktop
      - extension-manager

    flatpak_packages:
      - wps.Office
      - md.obsidian.Obsidian
      - com.brave.Browser
      - com.proton.pass
      - org.signal.Signal
      - com.github.zocker_160.Obfuscate

    github_tools:
      - repo: https://github.com/ropnop/kerbrute.git
        name: kerbrute
      - repo: https://github.com/carlospolop/PEASS-ng.git
        name: PEASS-ng
      - repo: https://github.com/samratashok/nishang.git
        name: nishang
      - repo: https://github.com/lefayjey/linWinPwn.git
        name: linWinPwn
      - repo: https://github.com/garrettfoster13/sccmhunter.git
        name: sccmhunter
      - repo: https://github.com/MWR-CyberSec/PXEThief.git
        name: PXEThief
      - repo: https://github.com/SpecterOps/bloodhound-cli.git
        name: bloodhound-cli
      - repo: https://github.com/Lmarkussen/EvilTelnet.git
        name: EvilTelnet
      - repo: https://github.com/Lmarkussen/EvilParser.git
        name: EvilParser
      - repo: https://github.com/Lmarkussen/EvilFTP.git
        name: EvilFTP
      - repo: https://github.com/Lmarkussen/Bruteforce_wordlist_nor.git
        name: Bruteforce_wordlist_nor
      - repo: https://github.com/danielmiessler/SecLists.git
        name: SecLists


  tasks:

    #################################################################
    # MIRRORLIST
    #################################################################
    - name: Install reflector
      community.general.pacman:
        name: reflector
        state: present

    - name: Generate fresh Arch Mirrorlist
      ansible.builtin.shell: reflector --latest 20 --sort rate --save /etc/pacman.d/mirrorlist


    #################################################################
    # PACMAN PACKAGES
    #################################################################
    - name: Install pacman packages
      community.general.pacman:
        name: "{{ pacman_packages }}"
        state: present
        update_cache: yes


    #################################################################
    # DOCKER SETUP
    #################################################################
    - name: Enable and start Docker daemon
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Notify user
      ansible.builtin.debug:
        msg: "You MUST log out and back in for docker group to take effect!"


    #################################################################
    # INSTALL YAY
    #################################################################
    - name: Clone yay repo
      become: no
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ user_home }}/yay"

    - name: Build yay
      become: no
      ansible.builtin.shell: |
        cd {{ user_home }}/yay
        makepkg --noconfirm -si
      args:
        creates: /usr/bin/yay


    #################################################################
    # AUR PACKAGES
    #################################################################
    - name: Install AUR packages
      become: no
      ansible.builtin.shell: yay -S --noconfirm {{ item }}
      loop: "{{ aur_packages }}"


    #################################################################
    # FLATPAK
    #################################################################
    - name: Add flathub repo
      ansible.builtin.shell: |
        flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpak packages
      ansible.builtin.shell: |
        flatpak install -y flathub {{ item }}
      loop: "{{ flatpak_packages }}"


    #################################################################
    # GITHUB TOOLS
    #################################################################
    - name: Create tools dir
      ansible.builtin.file:
        path: "{{ tools_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"

    - name: Clone tools (depth 1 if SecLists)
      become: no
      ansible.builtin.shell: |
        git clone --depth 1 {{ item.repo }} {{ tools_dir }}/{{ item.name }}
      loop: "{{ github_tools }}"

    - name: Fix permissions on tools
      ansible.builtin.file:
        path: "{{ tools_dir }}"
        recurse: yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"


    #################################################################
    # FISH SHELL
    #################################################################
    - name: Set fish as default shell
      ansible.builtin.shell: |
        chsh -s /usr/bin/fish {{ user }}

    - name: Ensure fish config dir exists
      become: no
      ansible.builtin.file:
        path: "{{ user_home }}/.config/fish"
        state: directory

    - name: Copy fish config
      ansible.builtin.copy:
        src: config.fish
        dest: "{{ user_home }}/.config/fish/config.fish"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"


    #################################################################
    # TMUX
    #################################################################
    - name: Ensure tmux config dir exists
      ansible.builtin.file:
        path: "{{ user_home }}/.config/tmux"
        state: directory

    - name: Copy tmux config
      ansible.builtin.copy:
        src: tmux.conf
        dest: "{{ user_home }}/.config/tmux/tmux.conf"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"

