---
- name: Setup Arch pentest workstation
  hosts: localhost
  become: true
  vars:
    user: "{{ lookup('env','SUDO_USER') or lookup('env','USER') }}"
    user_home: "/home/{{ user }}"
    tools_dir: "{{ user_home }}/tools"

  tasks:

  ###############################################################
  # MIRRORS / SYSTEM
  ###############################################################

  - name: Install prereqs
    pacman:
      name:
        - reflector
        - git
        - curl
        - base-devel
      state: present

  - name: Optimize pacman mirrors
    command: reflector --latest 20 --sort rate --save /etc/pacman.d/mirrorlist

  - name: Update pacman database and system
    pacman:
      update_cache: true
      upgrade: true


  ###############################################################
  # BLACKARCH REPO
  ###############################################################

  - name: Download BlackArch bootstrap
    get_url:
      url: https://blackarch.org/strap.sh
      dest: /tmp/strap.sh
      mode: '0755'

  - name: Install BlackArch repo
    command: /tmp/strap.sh


  ###############################################################
  # YAY BUILD
  ###############################################################

  - name: Install yay build deps
    pacman:
      name:
        - base-devel
        - go
        - git
      state: present

  - name: Clone yay
    become: false
    git:
      repo: https://aur.archlinux.org/yay.git
      dest: "{{ user_home }}/yay"
      update: true

  - name: Build yay (as user)
    become: false
    shell: |
      cd "{{ user_home }}/yay"
      makepkg --noconfirm -si


  ###############################################################
  # PACMAN PACKAGES  (netcat now correct)
  ###############################################################

  - name: Install pentest packages (pacman)
    pacman:
      name:
        - tmux
        - fish
        - grc
        - hashcat
        - john
        - hydra
        - sqlmap
        - impacket
        - dnsutils
        - ffuf
        - openvpn
        - responder
        - gobuster
        - evil-winrm
        - gowitness
        - masscan
        - netcat
        - certipy
      state: present


  ###############################################################
  # DOCKER
  ###############################################################

  - name: Install Docker + compose
    pacman:
      name:
        - docker
        - docker-compose
      state: present

  - name: Enable docker service
    systemd:
      name: docker
      enabled: true
      state: started

  - name: Add user to docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: true

  - name: Notify user about docker relog
    debug:
      msg: "Logout/Login required for docker permissions to take effect."


  ###############################################################
  # AUR PACKAGES (yay)
  ###############################################################

  - name: Install AUR packages via yay
    become: false
    shell: yay -S --noconfirm --needed {{ item }}
    loop:
      - brave-bin
      - burpsuite
      - slack-desktop
      - extension-manager


  ###############################################################
  # PIPX
  ###############################################################

  - name: Install pipx
    pacman:
      name: python-pipx
      state: present


  ###############################################################
  # CREATE ~/tools
  ###############################################################

  - name: Create tools directory
    file:
      path: "{{ tools_dir }}"
      state: directory
      mode: "0755"
      owner: "{{ user }}"
      group: "{{ user }}"


  ###############################################################
  # CLONE GITHUB TOOLS
  ###############################################################

  - name: Clone offensive tools into ~/tools
    become: false
    git:
      repo: "{{ item }}"
      dest: "{{ tools_dir }}/{{ item | basename | regex_replace('\\.git$','') }}"
      update: false
    loop:
      - https://github.com/lefayjey/linWinPwn.git
      - https://github.com/garrettfoster13/sccmhunter.git
      - https://github.com/MWR-CyberSec/PXEThief.git
      - https://github.com/SpecterOps/bloodhound-cli.git
      - https://github.com/Lmarkussen/EvilTelnet.git
      - https://github.com/Lmarkussen/EvilParser.git
      - https://github.com/Lmarkussen/EvilFTP.git
      - https://github.com/Lmarkussen/Bruteforce_wordlist_nor.git
      - https://github.com/OleFredrik1/remoteKrbRelayx.git


  ###############################################################
  # FISH CONFIG
  ###############################################################

  - name: Set fish default shell
    user:
      name: "{{ user }}"
      shell: /usr/bin/fish

  - name: Ensure fish config directory exists
    file:
      path: "{{ user_home }}/.config/fish"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: Install fish config
    copy:
      src: config.fish
      dest: "{{ user_home }}/.config/fish/config.fish"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'


  ###############################################################
  # DONE
  ###############################################################

  - name: Finished setup
    debug:
      msg: "COMPLETE — reboot recommended for docker + fish activation."

