---
- name: BlackArch + Pentest Desktop Setup
  hosts: localhost
  become: true
  vars:
    user: lars
    user_home: "/home/{{ user }}"

  tasks:

#################################################################
# BLACKARCH REPO
#################################################################
    - name: Install BlackArch repository
      ansible.builtin.shell: |
        curl -fsSL https://blackarch.org/strap.sh | bash
      args:
        creates: /etc/pacman.d/blackarch-mirrorlist

    - name: Update package databases
      ansible.builtin.pacman:
        update_cache: true

#################################################################
# PACMAN PACKAGES
#################################################################
    - name: Install pentest packages (pacman)
      ansible.builtin.pacman:
        name:
          - base-devel
          - go
          - wget
          - curl
          - unzip
          - python-pip
          - python-pipx
          - gobuster
          - hashcat
          - john
          - hydra
          - sqlmap
          - impacket
          - openvpn
          - responder
          - kerbrute
          - dnsutils
          - ffuf
          - netexec
          - nmap
          - masscan
          - netcat
          - gowitness
          - evil-winrm
          - tmux
          - fish
        state: present

#################################################################
# CREATE TOOLS DIRECTORY
#################################################################
    - name: Create Tools directory
      ansible.builtin.file:
        path: "{{ user_home }}/Tools"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

#################################################################
# CLONE REPOS
#################################################################
    - name: Clone pentest repos
      ansible.builtin.git:
        repo: "{{ item }}"
        dest: "{{ user_home }}/Tools/{{ item.split('/')[-1] }}"
      loop:
        - https://github.com/lefayjey/linWinPwn
        - https://github.com/garrettfoster13/sccmhunter
        - https://github.com/MWR-CyberSec/PXEThief
        - https://github.com/SpecterOps/bloodhound-cli
        - https://github.com/Lmarkussen/EvilTelnet
        - https://github.com/Lmarkussen/EvilParser
        - https://github.com/Lmarkussen/EvilFTP
        - https://github.com/Lmarkussen/Bruteforce_wordlist_nor
        - https://github.com/OleFredrik1/remoteKrbRelayx
      become_user: "{{ user }}"

#################################################################
# INSTALL HACK NERD FONT
#################################################################
    - name: Download Hack Nerd Font
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip
        dest: "{{ user_home }}/Hack.zip"

    - name: Create local fonts directory
      ansible.builtin.file:
        path: "{{ user_home }}/.local/share/fonts"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Extract Hack font
      ansible.builtin.unarchive:
        src: "{{ user_home }}/Hack.zip"
        dest: "{{ user_home }}/.local/share/fonts"
        remote_src: yes
      become_user: "{{ user }}"

#################################################################
# WALLPAPER
#################################################################
    - name: Copy bundled wallpaper
      ansible.builtin.copy:
        src: wallpaper.jpg
        dest: "{{ user_home }}/Pictures/wallpaper.jpg"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Set wallpaper
      ansible.builtin.shell: |
        gsettings set org.gnome.desktop.background picture-uri "file://{{ user_home }}/Pictures/wallpaper.jpg"
        gsettings set org.gnome.desktop.background picture-uri-dark "file://{{ user_home }}/Pictures/wallpaper.jpg"
      become_user: "{{ user }}"

#################################################################
# SET DEFAULT SHELL TO FISH
#################################################################
    - name: Set fish default shell
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /usr/bin/fish

#################################################################
# DONE
#################################################################
    - name: Finished
      ansible.builtin.debug:
        msg: "Setup completed. AD pentesting workstation ready."

