---
- name: Setup Arch pentest workstation
  hosts: localhost
  connection: local
  become: true

  vars:
    user: "{{ lookup('env','SUDO_USER') or lookup('env','USER') }}"
    user_home: "/home/{{ user }}"
    pics_dir: "{{ user_home }}/Pictures"
    repos_dir: "{{ user_home }}/repos"

  tasks:

  ###############################################################
  # BLACKARCH REPOSITORY
  ###############################################################
  - name: Install BlackArch repo script
    pacman:
      name: blackarch-installer
      state: present
    ignore_errors: true

  - name: Run BlackArch installer
    shell: |
      curl -O https://blackarch.org/strap.sh
      chmod +x strap.sh
      ./strap.sh
    args:
      chdir: "{{ user_home }}"
    ignore_errors: true

  ###############################################################
  # INITIAL PACMAN INSTALLS (before yay)
  ###############################################################
  - name: Install required packages before yay
    pacman:
      name:
        - base-devel
        - go
        - wget
        - curl
        - unzip
        - python-pip
        - python-pipx
        - flatpak
      state: present
      update_cache: true

  ###############################################################
  # BUILD AND INSTALL YAY
  ###############################################################
  - name: Clone yay
    ansible.builtin.git:
      repo: "https://aur.archlinux.org/yay.git"
      dest: "{{ user_home }}/yay"
    become_user: "{{ user }}"

  - name: Build yay
    shell: makepkg --noconfirm -si
    args:
      chdir: "{{ user_home }}/yay"
    become_user: "{{ user }}"

  ###############################################################
  # POST-YAY PACMAN PACKAGES
  ###############################################################
  - name: Install pentest packages (pacman)
    pacman:
      name:
        - gobuster
        - hashcat
        - john
        - hydra
        - sqlmap
        - impacket
        - openvpn
        - responder
        - kerbrute
        - dnsutils
        - ffuf
        - masscan
        - netcat
        - gowitness
        - evil-winrm
        - tmux
        - fish
        - grc
        - docker
        - docker-compose
      state: present

  ###############################################################
  # YAY AUR PACKAGES
  ###############################################################
  - name: Install AUR packages with yay
    become_user: "{{ user }}"
    shell: yay -S --noconfirm --needed brave-bin burpsuite slack-desktop extension-manager

  ###############################################################
  # DOCKER GROUP
  ###############################################################
  - name: Add user to docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: true

  - name: Notify user docker login is needed
    debug:
      msg: "Log out & back in for Docker changes"

  ###############################################################
  # GITHUB REPOS
  ###############################################################
  - name: Create repo folder
    file:
      path: "{{ repos_dir }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Clone pentest repos
    ansible.builtin.git:
      repo: "{{ item }}"
      dest: "{{ repos_dir }}/{{ item.split('/')[-1] }}"
      force: yes
    with_items:
      - "https://github.com/lefayjey/linWinPwn"
      - "https://github.com/garrettfoster13/sccmhunter"
      - "https://github.com/MWR-CyberSec/PXEThief"
      - "https://github.com/SpecterOps/bloodhound-cli"
      - "https://github.com/Lmarkussen/EvilTelnet"
      - "https://github.com/Lmarkussen/EvilParser"
      - "https://github.com/Lmarkussen/EvilFTP"
      - "https://github.com/Lmarkussen/Bruteforce_wordlist_nor"
      - "https://github.com/OleFredrik1/remoteKrbRelayx"
    become_user: "{{ user }}"

  ###############################################################
  # FLATPAK & OBFUSCATE
  ###############################################################
  - name: Install Obfuscate (flatpak)
    become_user: "{{ user }}"
    shell: flatpak install --noninteractive flathub com.github.hluk.copyq

  ###############################################################
  # DOTFILES (FISH + TMUX)
  ###############################################################
  - name: Ensure fish config folder exists
    file:
      path: "{{ user_home }}/.config/fish"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy fish config
    copy:
      src: config.fish
      dest: "{{ user_home }}/.config/fish/config.fish"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Ensure tmux config folder exists
    file:
      path: "{{ user_home }}/.config/tmux"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy tmux config
    copy:
      src: tmux.conf
      dest: "{{ user_home }}/.config/tmux/tmux.conf"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Set shell to fish
    user:
      name: "{{ user }}"
      shell: /usr/bin/fish

  ###############################################################
  # FONT: NerdFonts Hack
  ###############################################################
  - name: Download Hack NerdFont
    get_url:
      url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip"
      dest: "{{ pics_dir }}/Hack.zip"

  - name: Install NerdFont
    shell: |
      unzip -o Hack.zip -d /usr/share/fonts/nerd/
      fc-cache -fv
    args:
      chdir: "{{ pics_dir }}"

  ###############################################################
  # WALLPAPER (LOCAL)
  ###############################################################
  - name: Ensure Pictures dir exists
    file:
      path: "{{ pics_dir }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy wallpaper from repo
    copy:
      src: wallpaper.jpg
      dest: "{{ pics_dir }}/wallpaper.jpg"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Set wallpaper
    become_user: "{{ user }}"
    command: gsettings set org.gnome.desktop.background picture-uri "file://{{ pics_dir }}/wallpaper.jpg"

  ###############################################################
  # GNOME THEME (DRACULA)
  ###############################################################
  - name: Set Dracula interface theme
    become_user: "{{ user }}"
    command: gsettings set org.gnome.desktop.interface gtk-theme 'Dracula'

  ###############################################################
  # FINISHED
  ###############################################################
  - name: Completion summary
    debug:
      msg: "Setup complete. Log out and back in!"


